env: standard
runtime: nodejs16
service: default
handlers:
  - url: /assets
    static_dir: assets
    http_headers:
      Access-Control-Allow-Origin: "*"
  - url: /posts/(.+)/
    static_files: posts/\1/index.html
    upload: posts/(.+)/index.html
  - url: /(.+)
    static_files: \1
    upload: (.+)
  - url: /
    static_files: index.html
    upload: index.html
